# Triangular, pentagonal, and hexagonal
# Problem 45

"""
Triangle, pentagonal, and hexagonal numbers
are generated by the following formulae:

Triangle        Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n-1)/2        1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n-1)      1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from math import sqrt


def getTriangularNumber(n):
    return n*(n+1)/2


def isPentagonal(p):
    """ See problem 44 for deduction """
    n = (sqrt(6*p + .25) + .5)/3
    return n == int(n)


def isHexagonal(h):
    """
    If n is natural, then h is hexagonal

    h = n(2n-1)
    h = 2n^2 - n
    2h = 4n^2 - 2n
    2h + 1/4 = 4n^2 - 2n + 1/4
    2h + 1/4 = (2n - 1/2)^2
    sqrt(2h + 1/4) = 2n - 1/2
    (sqrt(2h + 1/4) + 1/2) / 2 = n
    (sqrt(2*h + .25) + .5) / 2 = n
    """

    n = (sqrt(2*h + .25) + .5) / 2
    return n == int(n)


def main():
    # I need to find the next triangular number after n=285
    answer = 0
    n = 286
    while answer == 0:
        triang = getTriangularNumber(n)
        n += 1
        # If triang number is pentagonal and hexagonal, its solved
        if isPentagonal(triang) and isHexagonal(triang):
            answer = triang

    print answer


if __name__ == "__main__":
    main()
