# Distinct powers
# Problem 29

"""
https://projecteuler.net/problem=29
How many distinct terms are in the sequence generated by a^b
for 2 <= a <= 100 and 2 <= b <= 100?
"""


def main():
    terms = []
    for a in range(2, 101):
        for b in range(2, 101):
            terms.append(a**b)

    # set() removes the duplicates
    # len() gives the number of elements
    print len(set(terms))


if __name__ == "__main__":
    main()
